### ISSUE TITLE
Fresh build?

### ISSUE THREAD

**Issue by EvanPurkhiser** [WhyNotHugo/docker-makepkg#10]
Seems like the latest image on docker hub is a bit out of date, some of my builds are failing here: https://travis-ci.com/EvanPurkhiser/PKGBUILDs

Does docker hub have a way to do cron style builds?

**Comment by WhyNotHugo** [comment]
I've triggered a rebuild now, but looks like docker hub won't allow automatic this.
Maybe I could hook up travis to run a cronned build that pings docker hub and makes it rebuild...?

**Comment by EvanPurkhiser** [comment]
Looks like latest is actually still 5 months old :/

**Comment by EvanPurkhiser** [comment]
Hmm, still seeing this using this image:

https://travis-ci.com/EvanPurkhiser/PKGBUILDs/jobs/230030882

```
:: Synchronizing package databases...
downloading core.db...
downloading extra.db...
downloading community.db...
resolving dependencies...
looking for conflicting packages...
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: systemd-libs and libsystemd are in conflict. Remove libsystemd? [y/N] 
:: systemd-libs and libsystemd are in conflict
Error installing repo packages
The command "docker run -v $TRAVIS_BUILD_DIR/$PACKAGE:/pkg whynothugo/makepkg" exited with 1.```

**Comment by WhyNotHugo** [comment]
I've pushed changes to this repo that _should_ rebuild the image nightly. We'll see at midnight UTC if it works.

Otherwise I'll follow up tomorrow on it.
