### ISSUE TITLE
failed to retrieve some files when trying to install build dependencies

### ISSUE THREAD

**Issue by startergo** [WhyNotHugo/docker-makepkg#23]
The issue is discussed here:
https://github.com/startergo/docker-makepkg/issues/1

**Comment by WhyNotHugo** [comment]
Can you still reproduce this? Wasn't this just an out-of-date mirror?

**Comment by startergo** [comment]
So originally they were working on a fresh install, but after a time I noticed that not all dependencies are accessible. Additionally @zocker-160 confirmed the issue on his machine.

**Comment by zocker-160** [comment]
You can always encounter this issue unless you run `pacman -Syu --noconfirm` on startup of the container.

The reason is very simple, if a package on the mirror changes after the build of the container, the package list inside the container is outdated and will cause issues.

**Comment by firecat53** [comment]
I'd suggest adding a `paru -Syu` or `pacman -Syu` to run.sh at the beginning of the script to solve this. Otherwise, you basically need to delete the image and rebuild it right before using it to build a package since the repos update so fast.

**Comment by evanpurkhiser** [comment]
I think we could probably make this an option. I'm going to go ahead and open a pull request.

I've also run into this again 😢

**Comment by WhyNotHugo** [comment]
Fixed via #25. Lemme know if you see this again.
