### ISSUE TITLE
Export dependens 

### ISSUE THREAD

**Issue by edombek** [WhyNotHugo/docker-makepkg#31]
Hi, what about of export dependens?

**Comment by WhyNotHugo** [comment]
What do you mean?

**Comment by edombek** [comment]
Export builded dependences, if i send EXPORT_PKG=1, i get only package, without aur dependences. Do not collect them separately...

**Comment by WhyNotHugo** [comment]
Oh, yeah, that's not implemented. I guess you can mount the path where `paru` saves the built packages onto the host.

**Comment by ptr1337** [comment]
> Oh, yeah, that's not implemented. I guess you can mount the path where `paru` saves the built packages onto the host.

Actually it would also work quite easy if changing in the makepkg.conf the PKGDST and then just move out the packages from there. Did used it for some time, worked fine.

**Comment by edombek** [comment]
Thanks!
